---
title: "Assignment-2"
author: "Manuel Bottino"
date: "`r Sys.Date()`"

output:
  pdf_document: 
    toc: true
    number_sections: true
    latex_engine: pdflatex
fig_caption: yes
urlcolor: blue
header-includes:
  - \usepackage{amssymb}
editor_options: 
  markdown: 
    wrap: 72
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(magrittr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(ggpubr)
library(bookdown)
library(plotly)
library(rstanarm)
library(Cairo)
library(rgl)
library(plot3D)
library(effects)
library(MASS)
library(car)
library(faraway)
library(leaps)
library(ROCR)
library(RColorBrewer)
library(ISLR2)
library(e1071)
library(class)
library(reshape2)
library(sads)
library(knitr)
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Excercise 1 - Risiko! is back, with friends




## Point a)
```{r}
df <- readRDS("~/Documents/GitHub/Computational-stat/Assignment 2/games_preprocessed.RDS")

plot(df$average_rating, df$yearpublished) # to see whether old board_games tend to be preferred more because of their assessed popularity

ggplot(data=df, aes(y=playingtime, x=as.factor(minplayers)))+ # As more player play are needed to start the game,                                                                 the average duration increases
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=FALSE)
```
## Point b)
```{r}
df= df[,-1:-2]
df=data.frame(scale(df))
```

```{r}
x=cov(df)
cor(df)
# We can get the same result using cov2cor
cov2cor(x)
```
They are equal. Fonte: https://math.stackexchange.com/questions/3780344/under-what-conditions-will-the-covariance-matrix-be-identical-to-the-correlation

## Point c)
```{r}

cov_var_sample=array(NA, dim=c(6,6,10))
for(i in 1:10){
cov_var_sample[,,i]=cov(data.frame(t(replicate(10, slice_sample(df,n=nrow(df), replace=TRUE)))[i,]))
}

se_cov_var=apply(cov_var_sample, c(1, 2), sd)



D2SUB    <- reshape2::melt(bootstrap_df_playingtime)
ggplot_playingtime = ggplot()+
  stat_ecdf(aes(x=D2SUB$value,group = D2SUB$Var2, col = "Bootstrap"))+
    stat_ecdf(aes(x=df$playingtime,col="Sample"),lwd=0.4)+
    xlab("Sample")+ggtitle("CDFs")+ylab("F")+
      scale_color_manual("",values = c("lightgray",1,4))+
  theme(text = element_text(size=14),legend.position = "bottom")
```


```{r}
x=var(df$maxplayers)*(2/(nrow(df)-1))^{1/2}


theta_star_maxplayer <- apply(bootstrap_df_maxplayer, 2, function(z) var(z))
theta_star_maxplayer <- apply(bootstrap_df_maxplayer, 2, function(z) var(z))
theta_star_maxplayer <- apply(bootstrap_df_maxplayer, 2, function(z) var(z))
theta_star_maxplayer <- apply(bootstrap_df_maxplayer, 2, function(z) var(z))
theta_star_maxplayer <- apply(bootstrap_df_maxplayer, 2, function(z) var(z))
theta_star_maxplayer <- apply(bootstrap_df_maxplayer, 2, function(z) var(z))

se_maxplayer = sd(theta_star_maxplayer)
se_maxplayer = sd(theta_star_maxplayer)
se_maxplayer = sd(theta_star_maxplayer)
se_maxplayer = sd(theta_star_maxplayer)
se_maxplayer = sd(theta_star_maxplayer)
se_maxplayer = sd(theta_star_maxplayer)

qplot( theta_star_maxplayer, col=I(4), fill=I("white"),bins=25)+
  xlab(TeX("$\\hat{\\theta}^*$")) + 
  ylab("Frequency") + 
  ggtitle("IQR Bootstrap distribution")
```







## Point d)

## Point e)

## Point f)

## Point g)

## Point h)


# Exercise 2 - We need some music!


## Point a)

## Point b)

## Point c)

## Point d)

## Point e)

## Point f)

## Point g)




